# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='commonlib',
    version='0.0.0',
    packages=['commonlib'],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        'appdirs==1.4.4', 'attrs==20.3.0', 'black==20.8b1',
        'certifi==2020.12.5', 'chardet==3.0.4', 'click==7.1.2',
        'commonlib==0.0.0', 'dnspython==2.0.0', 'email-validator==1.1.2',
        'fastapi==0.62.0', 'idna==2.10', 'iniconfig==1.1.1',
        'mypy-extensions==0.4.3', 'packaging==20.7', 'pathspec==0.8.1',
        'pluggy==0.13.1', 'py==1.9.0', 'pydantic==1.7.2', 'pyparsing==2.4.7',
        'pytest==6.1.2', 'regex==2020.11.13', 'requests==2.25.0',
        'sqlalchemy==1.3.20', 'starlette==0.13.6', 'toml==0.10.2',
        'typed-ast==1.4.1', 'typing-extensions==3.7.4.3', 'urllib3==1.26.2'
    ],
)
