"""Remove permission tables

Revision ID: 256b25a02536
Revises: 7380cb66ffb0
Create Date: 2020-12-01 14:54:16.655412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '256b25a02536'
down_revision = '7380cb66ffb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apipermission_id', table_name='apipermission')
    op.drop_index('ix_apipermission_name', table_name='apipermission')
    op.drop_table('apipermission')
    op.drop_table('api_permission_user_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_permission_user_type',
    sa.Column('user_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('api_permission_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['api_permission_id'], ['apipermission.id'], name='api_permission_user_type_api_permission_id_fkey'),
    sa.ForeignKeyConstraint(['user_type_id'], ['usertype.id'], name='api_permission_user_type_user_type_id_fkey')
    )
    op.create_table('apipermission',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('path_regex', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('method', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='apipermission_pkey')
    )
    op.create_index('ix_apipermission_name', 'apipermission', ['name'], unique=True)
    op.create_index('ix_apipermission_id', 'apipermission', ['id'], unique=False)
    # ### end Alembic commands ###
