"""Renamed column from 'route_name' to 'name'


Revision ID: 48fec505afa9
Revises: 67a4aa772095
Create Date: 2020-11-23 16:52:08.845177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48fec505afa9'
down_revision = '67a4aa772095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('name', sa.String(), nullable=True))
    op.create_index(op.f('ix_route_name'), 'route', ['name'], unique=True)
    op.drop_index('ix_route_route_name', table_name='route')
    op.drop_column('route', 'route_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('route_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_route_route_name', 'route', ['route_name'], unique=True)
    op.drop_index(op.f('ix_route_name'), table_name='route')
    op.drop_column('route', 'name')
    # ### end Alembic commands ###
