"""added new 'method' column to route table

Revision ID: 4e78738984e1
Revises: 48fec505afa9
Create Date: 2020-11-24 15:46:04.483675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e78738984e1'
down_revision = '48fec505afa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('method', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route', 'method')
    # ### end Alembic commands ###
