"""Add UserType model

Revision ID: 5d89ac18c757
Revises: 9b275f3da0c0
Create Date: 2020-11-18 16:19:56.586602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d89ac18c757'
down_revision = '9b275f3da0c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usertype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usertype_id'), 'usertype', ['id'], unique=False)
    op.add_column('user', sa.Column('user_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'usertype', ['user_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'user_type_id')
    op.drop_index(op.f('ix_usertype_id'), table_name='usertype')
    op.drop_table('usertype')
    # ### end Alembic commands ###
