"""Add created_at and updated_at timestamps to custom link table

Revision ID: 6a8ff81980ff
Revises: dd31b1ec0f9e
Create Date: 2020-11-27 11:00:21.625144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a8ff81980ff'
down_revision = 'dd31b1ec0f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
