"""Added email table

Revision ID: 7380cb66ffb0
Revises: 1277372ab9f9
Create Date: 2020-11-30 16:26:27.276049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7380cb66ffb0'
down_revision = '1277372ab9f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=True),
    sa.Column('recipient', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('template_dict', sa.String(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('extra_data', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_id'), 'email', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_id'), table_name='email')
    op.drop_table('email')
    # ### end Alembic commands ###
