"""renamed field on users model from 'creatd_devices' to 'devices

Revision ID: 9cd84aac06d0
Revises: 7cb162e05f64
Create Date: 2020-11-27 15:33:36.297619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cd84aac06d0'
down_revision = '7cb162e05f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
