"""Added unique constraint on UserType's name field

Revision ID: a1872115b09d
Revises: 5d89ac18c757
Create Date: 2020-11-18 17:03:20.603697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1872115b09d'
down_revision = '5d89ac18c757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'usertype', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usertype', type_='unique')
    # ### end Alembic commands ###
