"""refactored Routes model to become APIPermissions

Revision ID: af4c8b6033d5
Revises: b9962f7b26f7
Create Date: 2020-11-26 11:14:21.159719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af4c8b6033d5'
down_revision = 'b9962f7b26f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apipermission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('path_regex', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apipermission_id'), 'apipermission', ['id'], unique=False)
    op.create_index(op.f('ix_apipermission_name'), 'apipermission', ['name'], unique=True)
    op.create_table('api_permission_user_type',
    sa.Column('user_type_id', sa.Integer(), nullable=True),
    sa.Column('api_permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['api_permission_id'], ['apipermission.id'], ),
    sa.ForeignKeyConstraint(['user_type_id'], ['usertype.id'], )
    )
    op.drop_table('route_user_type')
    op.drop_index('ix_route_id', table_name='route')
    op.drop_index('ix_route_name', table_name='route')
    op.drop_table('route')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('route_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('path_regex', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='route_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_route_name', 'route', ['name'], unique=True)
    op.create_index('ix_route_id', 'route', ['id'], unique=False)
    op.create_table('route_user_type',
    sa.Column('user_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('route_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], name='route_user_type_route_id_fkey'),
    sa.ForeignKeyConstraint(['user_type_id'], ['usertype.id'], name='route_user_type_user_type_id_fkey')
    )
    op.drop_table('api_permission_user_type')
    op.drop_index(op.f('ix_apipermission_name'), table_name='apipermission')
    op.drop_index(op.f('ix_apipermission_id'), table_name='apipermission')
    op.drop_table('apipermission')
    # ### end Alembic commands ###
