"""added new 'path_regex' column to route table

Revision ID: b9962f7b26f7
Revises: 4e78738984e1
Create Date: 2020-11-24 16:49:37.195587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9962f7b26f7'
down_revision = '4e78738984e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('path_regex', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route', 'path_regex')
    # ### end Alembic commands ###
