"""Add self reference to user table to ensure we can track who created a user

Revision ID: deaacdfb29e8
Revises: 6a8ff81980ff
Create Date: 2020-11-27 11:26:39.020340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deaacdfb29e8'
down_revision = '6a8ff81980ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'created_by_id')
    # ### end Alembic commands ###
