"""renamed field on users model to 'devices' from 'created_devices

Revision ID: df4fb92ad2b1
Revises: 8bba44819b40
Create Date: 2020-11-27 12:45:25.359508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df4fb92ad2b1'
down_revision = '8bba44819b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
