"""Add column is_active and is_super_user to User model

Revision ID: fffed997c5ab
Revises: 36be7e3cbba9
Create Date: 2020-11-18 11:22:27.881556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fffed997c5ab'
down_revision = '36be7e3cbba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
