"""added column password reset token

Revision ID: 079f3b383c35
Revises: f412a5193d43
Create Date: 2020-12-10 13:38:58.108183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079f3b383c35'
down_revision = 'f412a5193d43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passwordresettoken', sa.Column('expires_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passwordresettoken', 'expires_at')
    # ### end Alembic commands ###
