"""added agent,id as foreign key on device table

Revision ID: 3848546b5695
Revises: bb5f68cbad42
Create Date: 2021-08-25 18:41:09.099054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3848546b5695'
down_revision = 'bb5f68cbad42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('device_agent_id_fkey', 'device', type_='foreignkey')
    op.create_foreign_key(None, 'device', 'agent', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device', type_='foreignkey')
    op.create_foreign_key('device_agent_id_fkey', 'device', 'user', ['agent_id'], ['id'])
    # ### end Alembic commands ###
