"""added self-reference on user table to map to the agent of the user

Revision ID: 42814233dda6
Revises: e6741f76abbe
Create Date: 2020-12-07 16:50:57.978301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42814233dda6'
down_revision = 'e6741f76abbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('agent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'agent_id')
    # ### end Alembic commands ###
