"""added deleted column to User Table

Revision ID: 471caecad289
Revises: a0ae64b81e35
Create Date: 2021-08-29 09:45:22.928746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '471caecad289'
down_revision = 'a0ae64b81e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'deleted')
    # ### end Alembic commands ###
