"""add agent_id field to device to note the agent currently assigned to the devices

Revision ID: 7be8e47022a4
Revises: 91bb360a5dac
Create Date: 2020-12-08 11:32:06.151316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be8e47022a4'
down_revision = '91bb360a5dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('agent_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'device', 'user', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device', type_='foreignkey')
    op.drop_column('device', 'agent_id')
    # ### end Alembic commands ###
