"""name column to device table

Revision ID: 8f23505131e1
Revises: e2062f501218
Create Date: 2021-06-04 17:45:36.678539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f23505131e1'
down_revision = '817e3d16846a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('name', sa.String(), nullable=False))
    op.create_index(op.f('ix_device_name'), 'device', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_name'), table_name='device')
    op.drop_column('device', 'name')
    # ### end Alembic commands ###
