"""retired user model column 'is_superuser'

Revision ID: 91bb360a5dac
Revises: 42814233dda6
Create Date: 2020-12-08 10:02:42.837941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91bb360a5dac'
down_revision = '42814233dda6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_superuser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
