"""remove used column from resettoken model

Revision ID: f412a5193d43
Revises: 0b31b05f6561
Create Date: 2020-12-10 12:54:03.238691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f412a5193d43'
down_revision = '0b31b05f6561' 
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passwordresettoken', 'used')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passwordresettoken', sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
